### ISSUE TITLE
This repo is empty!

### ISSUE THREAD

**Issue by yinghaochan** [thereactivestack/kickstart-redux#1]
Hey!

I'm a huge fan of the work done here, and have been using kickstart-hugeapp with my own implementation of Redux for many months now. 

I'd like to suggest several tweaks made after writing lots of code using the kickstart projects, and maybe contribute back in the form of this repo.

https://github.com/yinghaochan/redux-meteor

If you have any suggestions, I'd be happy to hear it, and would love to help out. The webpack package especially has helped me so much, being able to give back would be great.

Y

**Comment by eXon** [comment]
You can check the react-router-ssr package where you can see an example. This repo is probably going to be removed because I would rather write tutorials than create a kickstart project for anything under the sun.
